import { Navbar } from "@/components/navbar";
import { Footer } from "@/components/footer";

export const metadata = {
  title: "Privacy Policy - ProperlyTrade (Demo by MattyJacks.com)",
  description:
    "Privacy Policy for the ProperlyTrade demo site, operated by MattyJacks, a sole proprietorship in New Hampshire, USA.",
};

export default function PrivacyPolicyPage() {
  return (
    <>
      <Navbar />
      <main className="min-h-screen pt-32 pb-20">
        <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8">
          {/* AI-generated disclaimer */}
          <div className="mb-8 p-4 rounded-xl bg-orange-500/5 border border-orange-500/10">
            <p className="text-xs text-orange-400/80 leading-relaxed">
              <strong>Notice:</strong> This privacy policy was generated by AI
              and may be inaccurate or incomplete. This is a demo site built by{" "}
              <a
                href="https://mattyjacks.com"
                target="_blank"
                rel="noopener noreferrer"
                className="underline"
              >
                MattyJacks.com
              </a>
              . For questions, contact{" "}
              <a href="mailto:Matt@MattyJacks.com" className="underline">
                Matt@MattyJacks.com
              </a>
              . This document should not be relied upon as legal advice.
            </p>
          </div>

          <h1 className="text-4xl sm:text-5xl font-bold text-white mb-4">
            Privacy Policy
          </h1>
          <p className="text-sm text-white/30 mb-12">
            Last updated: March 13, 2026
          </p>

          <div className="prose prose-invert prose-sm max-w-none space-y-8">
            <section>
              <h2 className="text-xl font-semibold text-white mb-3">
                1. Introduction
              </h2>
              <p className="text-sm text-white/50 leading-relaxed">
                This Privacy Policy describes how ProperlyTrade (&quot;we,&quot;
                &quot;us,&quot; or &quot;our&quot;), a demo website operated by
                MattyJacks, a sole proprietorship registered in New Hampshire,
                USA, collects, uses, and shares information about you when you
                use our website and services. This is a demonstration website and
                comes with no warranties for use.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">
                2. Operator Information
              </h2>
              <div className="text-sm text-white/50 leading-relaxed space-y-2">
                <p>
                  <strong className="text-white/70">Business Name:</strong>{" "}
                  MattyJacks (Sole Proprietorship)
                </p>
                <p>
                  <strong className="text-white/70">Location:</strong> New
                  Hampshire, United States
                </p>
                <p>
                  <strong className="text-white/70">Contact Email:</strong>{" "}
                  <a
                    href="mailto:Matt@MattyJacks.com"
                    className="text-blue-400 hover:text-blue-300"
                  >
                    Matt@MattyJacks.com
                  </a>
                </p>
                <p>
                  <strong className="text-white/70">Website:</strong>{" "}
                  <a
                    href="https://mattyjacks.com"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-blue-400 hover:text-blue-300"
                  >
                    MattyJacks.com
                  </a>
                </p>
              </div>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">
                3. Information We Collect
              </h2>
              <div className="text-sm text-white/50 leading-relaxed space-y-4">
                <div>
                  <h3 className="text-base font-medium text-white/70 mb-2">
                    3.1 Information You Provide
                  </h3>
                  <ul className="list-disc list-inside space-y-1 ml-2">
                    <li>
                      Contact form submissions (name, email, company, message)
                    </li>
                    <li>
                      Account registration data if using Supabase authentication
                    </li>
                    <li>
                      AI chatbot conversation history (stored locally in your
                      browser)
                    </li>
                    <li>
                      API keys you voluntarily provide (stored locally in your
                      browser only, never on our servers)
                    </li>
                  </ul>
                </div>
                <div>
                  <h3 className="text-base font-medium text-white/70 mb-2">
                    3.2 Information Collected Automatically
                  </h3>
                  <ul className="list-disc list-inside space-y-1 ml-2">
                    <li>
                      Usage data and analytics via Vercel Analytics (our hosting
                      provider)
                    </li>
                    <li>
                      IP address, browser type, device information, and
                      operating system
                    </li>
                    <li>Pages visited, time spent, and referring URLs</li>
                    <li>Cookies and similar tracking technologies</li>
                  </ul>
                </div>
              </div>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">
                4. How We Use Your Information
              </h2>
              <ul className="text-sm text-white/50 leading-relaxed list-disc list-inside space-y-1 ml-2">
                <li>To provide and maintain the demo website</li>
                <li>To respond to contact form inquiries</li>
                <li>To process AI chatbot requests through third-party APIs</li>
                <li>To improve the website and user experience</li>
                <li>To comply with legal obligations</li>
                <li>To detect and prevent fraud or abuse</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">
                5. Third-Party Services
              </h2>
              <div className="text-sm text-white/50 leading-relaxed space-y-3">
                <p>We use the following third-party services:</p>
                <ul className="list-disc list-inside space-y-2 ml-2">
                  <li>
                    <strong className="text-white/70">Vercel</strong> - Website
                    hosting and deployment. Vercel may collect usage data and
                    analytics. See{" "}
                    <a
                      href="https://vercel.com/legal/privacy-policy"
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-blue-400 hover:text-blue-300 underline"
                    >
                      Vercel&apos;s Privacy Policy
                    </a>
                    .
                  </li>
                  <li>
                    <strong className="text-white/70">Cloudflare</strong> -
                    Domain registration and DNS services. Cloudflare may process
                    request data for security and performance. See{" "}
                    <a
                      href="https://www.cloudflare.com/privacypolicy/"
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-blue-400 hover:text-blue-300 underline"
                    >
                      Cloudflare&apos;s Privacy Policy
                    </a>
                    .
                  </li>
                  <li>
                    <strong className="text-white/70">Supabase</strong> -
                    Database and authentication services. If you create an
                    account, your authentication data is processed by Supabase.
                    See{" "}
                    <a
                      href="https://supabase.com/privacy"
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-blue-400 hover:text-blue-300 underline"
                    >
                      Supabase&apos;s Privacy Policy
                    </a>
                    .
                  </li>
                  <li>
                    <strong className="text-white/70">OpenAI</strong> - AI
                    chatbot responses are processed through OpenAI&apos;s API.
                    Your chat messages are sent to OpenAI for processing. See{" "}
                    <a
                      href="https://openai.com/policies/privacy-policy"
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-blue-400 hover:text-blue-300 underline"
                    >
                      OpenAI&apos;s Privacy Policy
                    </a>
                    .
                  </li>
                  <li>
                    <strong className="text-white/70">OpenRouter</strong> - An
                    alternative AI API routing service. If selected, your chat
                    messages are sent to OpenRouter. See{" "}
                    <a
                      href="https://openrouter.ai/privacy"
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-blue-400 hover:text-blue-300 underline"
                    >
                      OpenRouter&apos;s Privacy Policy
                    </a>
                    .
                  </li>
                </ul>
              </div>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">
                6. Data Storage and Security
              </h2>
              <div className="text-sm text-white/50 leading-relaxed space-y-2">
                <p>
                  Chat history and API keys you provide are stored locally in
                  your browser using localStorage. They are not transmitted to
                  or stored on our servers (except when sent to the AI API for
                  processing chat requests).
                </p>
                <p>
                  Account data (if applicable) is stored in Supabase&apos;s
                  infrastructure. Website data is hosted on Vercel&apos;s
                  infrastructure. We use industry-standard security measures but
                  cannot guarantee absolute security.
                </p>
              </div>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">
                7. Your Rights
              </h2>
              <div className="text-sm text-white/50 leading-relaxed space-y-2">
                <p>Depending on your jurisdiction, you may have the right to:</p>
                <ul className="list-disc list-inside space-y-1 ml-2">
                  <li>Access the personal data we hold about you</li>
                  <li>Request correction or deletion of your data</li>
                  <li>Object to or restrict processing of your data</li>
                  <li>Request data portability</li>
                  <li>Withdraw consent at any time</li>
                </ul>
                <p>
                  To exercise any of these rights, contact us at{" "}
                  <a
                    href="mailto:Matt@MattyJacks.com"
                    className="text-blue-400 hover:text-blue-300"
                  >
                    Matt@MattyJacks.com
                  </a>
                  .
                </p>
              </div>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">
                8. Cookies
              </h2>
              <p className="text-sm text-white/50 leading-relaxed">
                This website may use cookies and similar technologies for
                functionality and analytics. These may include session cookies,
                preference cookies, and analytics cookies set by our hosting
                provider Vercel. You can control cookies through your browser
                settings.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">
                9. Children&apos;s Privacy
              </h2>
              <p className="text-sm text-white/50 leading-relaxed">
                This website is not intended for children under 18. We do not
                knowingly collect personal information from children. If you
                believe we have collected information from a child, please
                contact us at{" "}
                <a
                  href="mailto:Matt@MattyJacks.com"
                  className="text-blue-400 hover:text-blue-300"
                >
                  Matt@MattyJacks.com
                </a>
                .
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">
                10. Changes to This Policy
              </h2>
              <p className="text-sm text-white/50 leading-relaxed">
                We may update this privacy policy from time to time. Changes
                will be posted on this page with an updated revision date. Your
                continued use of the website constitutes acceptance of any
                changes.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">
                11. Contact Us
              </h2>
              <div className="text-sm text-white/50 leading-relaxed space-y-2">
                <p>
                  If you have questions about this Privacy Policy, contact us:
                </p>
                <p>
                  <strong className="text-white/70">MattyJacks</strong>
                  <br />
                  New Hampshire, USA
                  <br />
                  Email:{" "}
                  <a
                    href="mailto:Matt@MattyJacks.com"
                    className="text-blue-400 hover:text-blue-300"
                  >
                    Matt@MattyJacks.com
                  </a>
                  <br />
                  Web:{" "}
                  <a
                    href="https://mattyjacks.com"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-blue-400 hover:text-blue-300"
                  >
                    MattyJacks.com
                  </a>
                </p>
              </div>
            </section>

            {/* Final AI disclaimer */}
            <div className="mt-12 p-4 rounded-xl bg-red-500/5 border border-red-500/10">
              <p className="text-xs text-red-400/70 leading-relaxed">
                <strong>Disclaimer:</strong> This Privacy Policy was generated
                by artificial intelligence and may contain inaccuracies,
                omissions, or errors. It is provided for demonstration purposes
                only as part of a demo website built by MattyJacks.com. This
                document does not constitute legal advice. Consult a qualified
                attorney for legally binding privacy policies. This demo site
                comes with no warranties of any kind, express or implied.
              </p>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}
