"use client";

import Link from "next/link";
import { LogoMark } from "@/components/logo-mark";

const footerLinks = {
  Solutions: [
    { href: "/features", label: "Prop CRM" },
    { href: "/features", label: "Broker CRM" },
    { href: "/features", label: "Trading APIs" },
    { href: "/features", label: "Risk Guard" },
  ],
  Company: [
    { href: "/about", label: "About Us" },
    { href: "/pricing", label: "Pricing" },
    { href: "/chat", label: "AI Trading" },
    { href: "/contact", label: "Contact" },
  ],
  Legal: [
    { href: "/legal/privacy-policy", label: "Privacy Policy" },
    { href: "/legal/terms", label: "Terms of Use" },
  ],
};

export function Footer() {
  return (
    <footer role="contentinfo" aria-label="Site footer" className="border-t border-white/[0.06] bg-[hsl(225,25%,3%)]">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-16">
        <div className="grid grid-cols-2 md:grid-cols-5 gap-8">
          <div className="col-span-2">
            <Link href="/" className="flex items-center gap-2 mb-4" aria-label="ProperlyTrade - Home">
              <LogoMark />
              <span className="text-lg font-semibold text-white">
                ProperlyTrade
              </span>
            </Link>
            <p className="text-sm text-white/40 max-w-xs leading-relaxed">
              All-in-one infrastructure for trading firms. Power your prop firm
              with complete trading technology, CRM, risk management, and
              automation tools.
            </p>
            <p className="text-xs text-white/25 mt-4">
              ProperlyTrade is a financial technology company. ProperlyTrade does
              not provide financial services.
            </p>
            <div className="mt-4 p-3 rounded-lg bg-orange-500/5 border border-orange-500/10">
              <p className="text-[10px] text-orange-400/60 leading-relaxed">
                <strong>Demo Site</strong> - Built by{" "}
                <a
                  href="https://mattyjacks.com"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="underline hover:text-orange-400"
                >
                  MattyJacks.com
                </a>
                {" "}
                for demonstration purposes. No warranties provided. Contact:{" "}
                <a
                  href="mailto:Matt@MattyJacks.com"
                  className="underline hover:text-orange-400"
                >
                  Matt@MattyJacks.com
                </a>
              </p>
            </div>
          </div>

          {Object.entries(footerLinks).map(([category, links]) => (
            <div key={category}>
              <h4 className="text-sm font-semibold text-white mb-4">
                {category}
              </h4>
              <ul className="space-y-3">
                {links.map((link) => (
                  <li key={link.label}>
                    <Link
                      href={link.href}
                      className="text-sm text-white/40 hover:text-white/70 transition-colors"
                    >
                      {link.label}
                    </Link>
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>

        <div className="mt-16 pt-8 border-t border-white/[0.06] space-y-4">
          <div className="flex flex-col sm:flex-row justify-between items-center gap-4">
            <p className="text-xs text-white/30">
              &copy; {new Date().getFullYear()} MattyJacks from New Hampshire, USA. All rights
              reserved.
            </p>
            <div className="flex flex-wrap justify-center gap-4 sm:gap-6">
              <Link
                href="/legal/privacy-policy"
                className="text-xs text-white/30 hover:text-white/50 transition-colors"
              >
                Privacy Policy
              </Link>
              <Link
                href="/legal/terms"
                className="text-xs text-white/30 hover:text-white/50 transition-colors"
              >
                Terms of Use
              </Link>
              <a
                href="mailto:Matt@MattyJacks.com"
                className="text-xs text-white/30 hover:text-white/50 transition-colors"
              >
                Matt@MattyJacks.com
              </a>
            </div>
          </div>
          <p className="text-[10px] text-white/15 text-center leading-relaxed">
            This is a demo site built by MattyJacks.com, a sole proprietorship in New Hampshire, USA.
            It comes with no warranties for use. All content, pricing, testimonials, and features shown are
            fictional and for demonstration purposes only. Legal documents on this site were generated by AI
            and may be inaccurate. Hosted on Vercel. Domain via Cloudflare. Database by Supabase.
          </p>
          <div className="text-center mt-4">
            <a
              href="#main-content"
              className="text-[10px] text-white/20 hover:text-white/40 transition-colors"
            >
              Back to top
            </a>
          </div>
        </div>
      </div>
    </footer>
  );
}
