"use client";

import { useState, useEffect } from "react";
import { Navbar } from "@/components/navbar";
import { ChatWidget } from "@/components/chat/chat-widget";
import { ApiKeySettings } from "@/components/chat/api-key-settings";
import { AlertTriangle, Sparkles, Coins, TrendingUp } from "lucide-react";
import {
  loadCredits,
  setOwnApiKey,
  CreditState,
  CREDIT_CONSTANTS,
  getByokDailyCreditsDisplay,
} from "@/lib/credits";

const API_KEY_STORAGE = "pt_api_keys";

interface StoredKeys {
  openai: string;
  openrouter: string;
  provider: "openai" | "openrouter";
}

function loadStoredKeys(): StoredKeys {
  if (typeof window === "undefined")
    return { openai: "", openrouter: "", provider: "openai" };
  const stored = localStorage.getItem(API_KEY_STORAGE);
  if (!stored) return { openai: "", openrouter: "", provider: "openai" };
  return JSON.parse(stored);
}

function saveStoredKeys(keys: StoredKeys) {
  if (typeof window === "undefined") return;
  localStorage.setItem(API_KEY_STORAGE, JSON.stringify(keys));
}

export default function ChatPage() {
  const [provider, setProvider] = useState<"openai" | "openrouter">("openai");
  const [openaiKey, setOpenaiKey] = useState("");
  const [openrouterKey, setOpenrouterKey] = useState("");
  const [credits, setCredits] = useState<CreditState | null>(null);
  const [disclaimerAccepted, setDisclaimerAccepted] = useState(false);

  useEffect(() => {
    const keys = loadStoredKeys();
    setProvider(keys.provider);
    setOpenaiKey(keys.openai);
    setOpenrouterKey(keys.openrouter);
    setCredits(loadCredits());

    const accepted = localStorage.getItem("pt_disclaimer_accepted");
    if (accepted === "true") setDisclaimerAccepted(true);
  }, []);

  useEffect(() => {
    saveStoredKeys({ openai: openaiKey, openrouter: openrouterKey, provider });

    const hasKey = !!(openaiKey || openrouterKey);
    const currentCredits = loadCredits();
    if (currentCredits.hasOwnApiKey !== hasKey) {
      const updated = setOwnApiKey(currentCredits, hasKey);
      setCredits(updated);
    }
  }, [openaiKey, openrouterKey, provider]);

  const acceptDisclaimer = () => {
    setDisclaimerAccepted(true);
    localStorage.setItem("pt_disclaimer_accepted", "true");
  };

  // Disclaimer gate
  if (!disclaimerAccepted) {
    return (
      <>
        <Navbar />
        <main className="min-h-screen pt-28 pb-16">
          <div className="mx-auto max-w-2xl px-4">
            <div className="rounded-2xl bg-white/[0.02] border border-white/[0.06] p-8 sm:p-12">
              <div className="flex items-center gap-3 mb-6">
                <div className="h-12 w-12 rounded-xl bg-orange-500/10 border border-orange-500/20 flex items-center justify-center">
                  <AlertTriangle className="h-6 w-6 text-orange-400" />
                </div>
                <h1 className="text-2xl font-bold text-white">
                  Important Disclaimer
                </h1>
              </div>

              <div className="space-y-4 mb-8">
                <div className="p-4 rounded-xl bg-blue-500/5 border border-blue-500/10">
                  <p className="text-xs text-blue-400/70 leading-relaxed">
                    <strong>Demo Site</strong> - This is a demonstration website
                    built by{" "}
                    <a
                      href="https://mattyjacks.com"
                      target="_blank"
                      rel="noopener noreferrer"
                      className="underline"
                    >
                      MattyJacks.com
                    </a>
                    , a sole proprietorship in New Hampshire, USA. It comes with
                    no warranties for use. Contact:{" "}
                    <a
                      href="mailto:Matt@MattyJacks.com"
                      className="underline"
                    >
                      Matt@MattyJacks.com
                    </a>
                  </p>
                </div>

                <div className="p-4 rounded-xl bg-red-500/5 border border-red-500/10">
                  <p className="text-sm text-red-400 font-medium mb-2">
                    This AI trading assistant does NOT provide financial advice.
                  </p>
                  <p className="text-xs text-red-400/60 leading-relaxed">
                    ProperlyTrade AI is purely experimental and untested. All
                    responses are generated by artificial intelligence and should
                    not be construed as investment advice, financial guidance, or
                    trading recommendations.
                  </p>
                </div>

                <div className="p-4 rounded-xl bg-orange-500/5 border border-orange-500/10">
                  <p className="text-sm text-orange-400 font-medium mb-2">
                    Use at your own risk.
                  </p>
                  <p className="text-xs text-orange-400/60 leading-relaxed">
                    Trading involves significant risk of financial loss. Past
                    performance does not guarantee future results. You should
                    never trade based solely on AI-generated suggestions. Always
                    do your own research and consider consulting with a licensed
                    financial advisor.
                  </p>
                </div>

                <div className="p-4 rounded-xl bg-white/[0.02] border border-white/[0.06]">
                  <p className="text-sm text-white/60 font-medium mb-2">
                    By proceeding, you acknowledge:
                  </p>
                  <ul className="space-y-2 text-xs text-white/40">
                    <li className="flex items-start gap-2">
                      <span className="text-white/20 mt-0.5">1.</span>
                      This is a demo site by MattyJacks.com with no warranties
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-white/20 mt-0.5">2.</span>
                      This tool is experimental and untested
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-white/20 mt-0.5">3.</span>
                      AI responses are not financial advice
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-white/20 mt-0.5">4.</span>
                      You accept full responsibility for any trading decisions
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-white/20 mt-0.5">5.</span>
                      MattyJacks is not liable for any financial losses
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-white/20 mt-0.5">6.</span>
                      You will not rely solely on AI for trading decisions
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-white/20 mt-0.5">7.</span>
                      You have read the{" "}
                      <a href="/legal/terms" className="text-blue-400 underline">Terms of Use</a>{" "}
                      and{" "}
                      <a href="/legal/privacy-policy" className="text-blue-400 underline">Privacy Policy</a>
                    </li>
                  </ul>
                </div>
              </div>

              <button
                onClick={acceptDisclaimer}
                className="w-full px-8 py-4 text-base font-medium text-white bg-gradient-to-r from-blue-600 to-blue-500 hover:from-blue-500 hover:to-blue-400 rounded-xl transition-all duration-300 shadow-lg shadow-blue-500/20"
              >
                I Understand and Accept the Risks
              </button>
            </div>
          </div>
        </main>
      </>
    );
  }

  const hasOwnKey = !!(openaiKey || openrouterKey);
  const byokDisplay = getByokDailyCreditsDisplay();
  const dailyCreditsExact = hasOwnKey
    ? CREDIT_CONSTANTS.FREE_CREDITS_PER_DAY * CREDIT_CONSTANTS.BYOK_MULTIPLIER
    : CREDIT_CONSTANTS.FREE_CREDITS_PER_DAY;
  const dailyCreditsInt = Math.floor(dailyCreditsExact);
  const maxCreditsExact = hasOwnKey
    ? CREDIT_CONSTANTS.MAX_FREE_CREDITS * CREDIT_CONSTANTS.BYOK_MULTIPLIER
    : CREDIT_CONSTANTS.MAX_FREE_CREDITS;
  const maxCreditsInt = Math.floor(maxCreditsExact);

  return (
    <>
      <Navbar />
      <main id="main-content" className="min-h-screen pt-24">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="flex flex-col lg:flex-row gap-6 h-[calc(100vh-7rem)]">
            {/* Sidebar */}
            <div className="lg:w-80 flex-shrink-0 space-y-4 overflow-y-auto">
              {/* Model info */}
              <div className="rounded-2xl bg-white/[0.02] border border-white/[0.06] p-5">
                <div className="flex items-center gap-3 mb-3">
                  <div className="h-9 w-9 rounded-lg bg-blue-500/10 border border-blue-500/20 flex items-center justify-center">
                    <Sparkles className="h-4 w-4 text-blue-400" />
                  </div>
                  <div>
                    <p className="text-sm font-medium text-white">
                      GPT-5.4 Latest
                    </p>
                    <p className="text-[10px] text-white/30">
                      via {provider === "openai" ? "OpenAI" : "OpenRouter"}
                    </p>
                  </div>
                </div>
                <p className="text-xs text-white/30 leading-relaxed">
                  Powered by the latest GPT-5.4 model for advanced trading
                  analysis. Supports Forex, Futures, Crypto, Equities, and
                  Options.
                </p>
              </div>

              {/* Credit summary */}
              <div className="rounded-2xl bg-white/[0.02] border border-white/[0.06] p-5">
                <div className="flex items-center gap-3 mb-4">
                  <div className="h-9 w-9 rounded-lg bg-yellow-500/10 border border-yellow-500/20 flex items-center justify-center">
                    <Coins className="h-4 w-4 text-yellow-400" />
                  </div>
                  <div>
                    <p className="text-sm font-medium text-white">Credits</p>
                    <p className="text-[10px] text-white/30">
                      +<span
                        title={hasOwnKey ? `${dailyCreditsExact} (\u03C0 \u00D7 ${CREDIT_CONSTANTS.FREE_CREDITS_PER_DAY} credits/day with BYOK bonus)` : undefined}
                        className={hasOwnKey ? "cursor-help border-b border-dotted border-white/20" : ""}
                      >{dailyCreditsInt}</span>/day, <span
                        title={hasOwnKey ? `${maxCreditsExact}` : undefined}
                        className={hasOwnKey ? "cursor-help border-b border-dotted border-white/20" : ""}
                      >{maxCreditsInt}</span> max
                    </p>
                  </div>
                </div>

                <div className="space-y-2">
                  <div className="flex justify-between text-xs">
                    <span className="text-white/40">Balance</span>
                    <span className="text-white font-medium">
                      {credits?.balance ?? 0}
                    </span>
                  </div>
                  <div className="flex justify-between text-xs">
                    <span className="text-white/40">Daily refill</span>
                    <span
                      className={`text-white/60 ${hasOwnKey ? "cursor-help border-b border-dotted border-white/20" : ""}`}
                      title={hasOwnKey ? `${dailyCreditsExact} (${byokDisplay.formula} credits/day with BYOK bonus)` : undefined}
                    >{dailyCreditsInt}</span>
                  </div>
                  <div className="flex justify-between text-xs">
                    <span className="text-white/40">Overage rate</span>
                    <span className="text-white/60">
                      ${CREDIT_CONSTANTS.OVERAGE_COST_PER_CREDIT}/prompt
                    </span>
                  </div>
                  {credits && credits.overageCreditsUsed > 0 && (
                    <div className="flex justify-between text-xs pt-1 border-t border-white/[0.04]">
                      <span className="text-orange-400/60">
                        Today&apos;s overage
                      </span>
                      <span className="text-orange-400">
                        {credits.overageCreditsUsed} ($
                        {(
                          credits.overageCreditsUsed *
                          CREDIT_CONSTANTS.OVERAGE_COST_PER_CREDIT
                        ).toFixed(2)}
                        )
                      </span>
                    </div>
                  )}
                </div>
              </div>

              {/* API Key Settings */}
              <ApiKeySettings
                provider={provider}
                onProviderChange={setProvider}
                openaiKey={openaiKey}
                onOpenaiKeyChange={setOpenaiKey}
                openrouterKey={openrouterKey}
                onOpenrouterKeyChange={setOpenrouterKey}
              />

              {/* Disclaimer reminder */}
              <div className="rounded-2xl bg-orange-500/5 border border-orange-500/10 p-4">
                <div className="flex items-start gap-2">
                  <AlertTriangle className="h-4 w-4 text-orange-400 flex-shrink-0 mt-0.5" />
                  <div className="text-[10px] text-orange-400/60 leading-relaxed space-y-1.5">
                    <p>
                      This AI is experimental and untested. It does not provide
                      financial advice. Trade at your own risk.
                    </p>
                    <p>
                      Demo site by{" "}
                      <a
                        href="https://mattyjacks.com"
                        target="_blank"
                        rel="noopener noreferrer"
                        className="underline hover:text-orange-400"
                      >
                        MattyJacks.com
                      </a>
                      {" "}- No warranties.{" "}
                      <a href="/legal/terms" className="underline hover:text-orange-400">Terms</a>
                      {" "}&bull;{" "}
                      <a href="/legal/privacy-policy" className="underline hover:text-orange-400">Privacy</a>
                    </p>
                  </div>
                </div>
              </div>
            </div>

            {/* Chat area */}
            <div className="flex-1 rounded-2xl bg-white/[0.01] border border-white/[0.06] overflow-hidden flex flex-col min-h-0">
              {/* Chat header */}
              <div className="flex items-center gap-3 px-5 py-4 border-b border-white/[0.06] bg-white/[0.01]">
                <div className="h-8 w-8 rounded-lg bg-gradient-to-br from-blue-500 to-cyan-400 flex items-center justify-center">
                  <TrendingUp className="h-4 w-4 text-white" />
                </div>
                <div>
                  <h2 className="text-sm font-semibold text-white">
                    ProperlyTrade AI
                  </h2>
                  <p className="text-[10px] text-white/30">
                    Experimental Trading Assistant - Not Financial Advice
                  </p>
                </div>
              </div>

              <ChatWidget
                provider={provider}
                userOpenAIKey={openaiKey}
                userOpenRouterKey={openrouterKey}
              />
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
