import { Navbar } from "@/components/navbar";
import { Footer } from "@/components/footer";

export const metadata = {
  title: "Terms of Use - ProperlyTrade (Demo by MattyJacks.com)",
  description:
    "Terms of Use for the ProperlyTrade demo site, operated by MattyJacks, a sole proprietorship in New Hampshire, USA.",
};

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <main className="min-h-screen pt-32 pb-20">
        <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8">
          {/* AI-generated disclaimer */}
          <div className="mb-8 p-4 rounded-xl bg-orange-500/5 border border-orange-500/10">
            <p className="text-xs text-orange-400/80 leading-relaxed">
              <strong>Notice:</strong> These Terms of Use were generated by AI
              and may be inaccurate or incomplete. This is a demo site built by{" "}
              <a
                href="https://mattyjacks.com"
                target="_blank"
                rel="noopener noreferrer"
                className="underline"
              >
                MattyJacks.com
              </a>
              . For questions, contact{" "}
              <a href="mailto:Matt@MattyJacks.com" className="underline">
                Matt@MattyJacks.com
              </a>
              . This document should not be relied upon as legal advice.
            </p>
          </div>

          <h1 className="text-4xl sm:text-5xl font-bold text-white mb-4">
            Terms of Use
          </h1>
          <p className="text-sm text-white/30 mb-12">
            Last updated: March 13, 2026
          </p>

          <div className="prose prose-invert prose-sm max-w-none space-y-8">
            <section>
              <h2 className="text-xl font-semibold text-white mb-3">
                1. Acceptance of Terms
              </h2>
              <p className="text-sm text-white/50 leading-relaxed">
                By accessing or using ProperlyTrade (the &quot;Site&quot;), a
                demonstration website operated by MattyJacks, a sole
                proprietorship in New Hampshire, USA, you agree to be bound by
                these Terms of Use. If you do not agree, do not use this Site.
                This is a demo site built for demonstration purposes and comes
                with absolutely no warranties for use of any kind, express or
                implied.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">
                2. Demo Site Disclaimer
              </h2>
              <div className="text-sm text-white/50 leading-relaxed space-y-3">
                <div className="p-4 rounded-xl bg-red-500/5 border border-red-500/10">
                  <p className="text-red-400/80">
                    <strong>THIS IS A DEMONSTRATION WEBSITE.</strong> It was
                    built by MattyJacks.com for portfolio and demonstration
                    purposes. The Site, its content, features, and any services
                    described herein are provided &quot;AS IS&quot; and &quot;AS
                    AVAILABLE&quot; without any warranties of any kind. Nothing
                    on this Site constitutes a real product offering, financial
                    advice, or binding commitment.
                  </p>
                </div>
                <p>
                  ProperlyTrade is a fictional brand created for this demo. Any
                  resemblance to actual companies, products, or services is
                  coincidental. The pricing, features, testimonials, team
                  members, and statistics shown on this site are fictional and
                  for demonstration purposes only.
                </p>
              </div>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">
                3. Operator Information
              </h2>
              <div className="text-sm text-white/50 leading-relaxed space-y-2">
                <p>
                  <strong className="text-white/70">Business Name:</strong>{" "}
                  MattyJacks (Sole Proprietorship)
                </p>
                <p>
                  <strong className="text-white/70">State of Operation:</strong>{" "}
                  New Hampshire, United States
                </p>
                <p>
                  <strong className="text-white/70">Contact:</strong>{" "}
                  <a
                    href="mailto:Matt@MattyJacks.com"
                    className="text-blue-400 hover:text-blue-300"
                  >
                    Matt@MattyJacks.com
                  </a>
                </p>
                <p>
                  <strong className="text-white/70">Website:</strong>{" "}
                  <a
                    href="https://mattyjacks.com"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-blue-400 hover:text-blue-300"
                  >
                    MattyJacks.com
                  </a>
                </p>
              </div>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">
                4. Technology Stack and Third-Party Services
              </h2>
              <div className="text-sm text-white/50 leading-relaxed space-y-3">
                <p>
                  This Site uses the following third-party services. By using
                  this Site, you acknowledge that your data may be processed by
                  these services according to their respective terms and privacy
                  policies:
                </p>
                <ul className="list-disc list-inside space-y-2 ml-2">
                  <li>
                    <strong className="text-white/70">Vercel</strong> - Website
                    hosting, deployment, and serverless functions. Your requests
                    are processed through Vercel&apos;s infrastructure.
                  </li>
                  <li>
                    <strong className="text-white/70">Cloudflare</strong> -
                    Domain name registration and DNS management. Cloudflare may
                    cache and route your requests for performance and security.
                  </li>
                  <li>
                    <strong className="text-white/70">Supabase</strong> -
                    Database and authentication backend. If you create an
                    account, your credentials are managed through Supabase.
                  </li>
                  <li>
                    <strong className="text-white/70">OpenAI</strong> - AI
                    language model API used by the experimental trading chatbot
                    feature. Messages you send to the chatbot are transmitted to
                    OpenAI for processing.
                  </li>
                  <li>
                    <strong className="text-white/70">OpenRouter</strong> -
                    Alternative AI API routing service available as a chatbot
                    backend option.
                  </li>
                  <li>
                    <strong className="text-white/70">Next.js</strong> - The
                    open-source React framework used to build this Site.
                  </li>
                </ul>
              </div>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">
                5. AI Trading Chatbot
              </h2>
              <div className="text-sm text-white/50 leading-relaxed space-y-3">
                <div className="p-4 rounded-xl bg-red-500/5 border border-red-500/10">
                  <p className="text-red-400/80">
                    <strong>THE AI TRADING CHATBOT IS EXPERIMENTAL AND
                    UNTESTED.</strong> It does NOT provide financial advice.
                    All AI-generated content is for educational and
                    entertainment purposes only. You must not rely on AI
                    responses for trading or investment decisions.
                  </p>
                </div>
                <p>
                  The AI chatbot feature uses third-party language models
                  (currently GPT-5.4 via OpenAI or OpenRouter). By using this
                  feature, you acknowledge:
                </p>
                <ul className="list-disc list-inside space-y-1 ml-2">
                  <li>AI responses may be inaccurate, misleading, or wrong</li>
                  <li>
                    Nothing the AI says constitutes financial, investment, or
                    trading advice
                  </li>
                  <li>
                    Trading involves significant risk of financial loss
                  </li>
                  <li>
                    You assume full responsibility for any actions taken based on
                    AI responses
                  </li>
                  <li>
                    MattyJacks is not liable for any losses resulting from use of
                    the AI feature
                  </li>
                  <li>
                    Your messages are sent to third-party AI providers for
                    processing
                  </li>
                  <li>
                    If you provide your own API keys, you are responsible for
                    associated costs
                  </li>
                </ul>
              </div>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">
                6. Credit System
              </h2>
              <div className="text-sm text-white/50 leading-relaxed space-y-2">
                <p>
                  The AI chatbot operates on a credit system. Free users receive
                  10 credits per day (accumulating to a maximum of 100). Users
                  who provide their own API keys receive \u03C0x (Pi times) the daily
                  allocation (~31/day, ~314 max). Overage usage beyond free
                  credits may incur charges as detailed on the Pricing page.
                </p>
                <p>
                  Credit balances, pricing, and overage rates are subject to
                  change at any time without notice. As this is a demo site, the
                  credit system is for demonstration purposes and actual billing
                  may not be implemented.
                </p>
              </div>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">
                7. User API Keys
              </h2>
              <div className="text-sm text-white/50 leading-relaxed space-y-2">
                <p>
                  If you choose to provide your own OpenAI or OpenRouter API
                  keys:
                </p>
                <ul className="list-disc list-inside space-y-1 ml-2">
                  <li>
                    Keys are stored only in your browser&apos;s local storage
                  </li>
                  <li>
                    Keys are sent directly to the respective API provider via our
                    server-side API route
                  </li>
                  <li>
                    We do not permanently store or log your API keys on our
                    servers
                  </li>
                  <li>
                    You are solely responsible for any charges incurred on your
                    API accounts
                  </li>
                  <li>
                    You should ensure your API keys have appropriate usage limits
                    set
                  </li>
                </ul>
              </div>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">
                8. Limitation of Liability
              </h2>
              <div className="text-sm text-white/50 leading-relaxed space-y-2">
                <p>
                  TO THE MAXIMUM EXTENT PERMITTED BY LAW, MATTYJACKS AND ITS
                  OWNER SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL,
                  SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT
                  LIMITED TO LOSS OF PROFITS, DATA, USE, OR GOODWILL, ARISING
                  FROM OR RELATED TO YOUR USE OF THIS DEMO SITE.
                </p>
                <p>
                  This includes, without limitation, any damages arising from:
                  use of or inability to use the Site; AI-generated content;
                  trading or investment decisions; unauthorized access to your
                  data; or any third-party services used by the Site.
                </p>
                <p>
                  IN NO EVENT SHALL OUR TOTAL LIABILITY EXCEED $0 USD, AS THIS
                  IS A FREE DEMO SITE.
                </p>
              </div>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">
                9. Disclaimer of Warranties
              </h2>
              <p className="text-sm text-white/50 leading-relaxed">
                THIS SITE IS PROVIDED &quot;AS IS&quot; AND &quot;AS
                AVAILABLE&quot; WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS,
                IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING BUT NOT LIMITED TO
                WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,
                TITLE, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SITE
                WILL BE UNINTERRUPTED, ERROR-FREE, SECURE, OR FREE OF VIRUSES
                OR OTHER HARMFUL COMPONENTS.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">
                10. Intellectual Property
              </h2>
              <p className="text-sm text-white/50 leading-relaxed">
                The Site&apos;s code, design, and content are the property of
                MattyJacks unless otherwise noted. The &quot;ProperlyTrade&quot;
                name and branding are used for demonstration purposes. All
                third-party trademarks, logos, and brand names referenced on
                this Site belong to their respective owners.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">
                11. Governing Law
              </h2>
              <p className="text-sm text-white/50 leading-relaxed">
                These Terms shall be governed by and construed in accordance
                with the laws of the State of New Hampshire, United States,
                without regard to its conflict of law provisions. Any disputes
                arising from these Terms or your use of the Site shall be
                resolved in the courts of New Hampshire.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">
                12. Changes to These Terms
              </h2>
              <p className="text-sm text-white/50 leading-relaxed">
                We reserve the right to modify these Terms at any time. Changes
                will be posted on this page. Your continued use of the Site
                after changes constitutes acceptance of the updated Terms.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">
                13. Contact
              </h2>
              <div className="text-sm text-white/50 leading-relaxed space-y-2">
                <p>For questions about these Terms of Use:</p>
                <p>
                  <strong className="text-white/70">MattyJacks</strong>
                  <br />
                  New Hampshire, USA
                  <br />
                  Email:{" "}
                  <a
                    href="mailto:Matt@MattyJacks.com"
                    className="text-blue-400 hover:text-blue-300"
                  >
                    Matt@MattyJacks.com
                  </a>
                  <br />
                  Web:{" "}
                  <a
                    href="https://mattyjacks.com"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-blue-400 hover:text-blue-300"
                  >
                    MattyJacks.com
                  </a>
                </p>
              </div>
            </section>

            {/* Final AI disclaimer */}
            <div className="mt-12 p-4 rounded-xl bg-red-500/5 border border-red-500/10">
              <p className="text-xs text-red-400/70 leading-relaxed">
                <strong>Disclaimer:</strong> These Terms of Use were generated
                by artificial intelligence and may contain inaccuracies,
                omissions, or errors. They are provided for demonstration
                purposes only as part of a demo website built by
                MattyJacks.com. This document does not constitute legal advice.
                Consult a qualified attorney for legally binding terms of
                service. This demo site comes with no warranties of any kind,
                express or implied.
              </p>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}
